/* Problem 1: Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold,
and total sales value. */
select top 10
p.product_name,
sum(oi.quantity) AS total_quantity_sold,
sum(oi.quantity * oi.price_per_unit) AS total_sales_value
from order_items as oi
left join products as p 
on oi.product_id = p.product_id
group by p.product_id, p.product_name
order by total_sales_value desc;

/* Problem 2: Show the revenue for each category and show how much each category contributes to the total revenue as a percentage.*/
with category_revenue as
(
select
    c.category_id,
    c.category_name,
    sum(oi.quantity * oi.price_per_unit) as total_revenue
from order_items as oi
left join products as p
on oi.product_id = p.product_id
left join category as c
on p.category_id = c.category_id 
group by c.category_id, c.category_name 
)
select
    category_id,
    category_name,
    round(
        (total_revenue * 100.0)/sum(total_revenue) over(),2
        ) as revenue_percentage,
        total_revenue
from category_revenue
order by total_revenue desc;

/* Problem 3. For every customer, find the average amount of money they spend per order. 
Only show customers who have placed more than 5 orders. */
with order_total as 
(
select 
    o.order_id,
    o.customer_id,
    sum(oi.quantity * oi.price_per_unit) as order_value
from orders as o
left join order_items as oi
on o.order_id = oi.order_id
group by 
o.order_id,
o.customer_id
)
select
    c.customer_id,
    c.first_name,
    c.last_name,
    count(*) as number_of_orders,
    round(avg(ot.order_value),2) as avg_order_value
from order_total as ot
left join customers as c
on c.customer_id = ot.customer_id
group by 
    c.customer_id,
    c.first_name,
    c.last_name
having count(*) > 5
order by avg_order_value desc;

/* Problem 4: For each month in the most recent 12 months, calculate the total sales made during that month.
Also show the previous month’s sales beside it so you can compare month-to-month performance.*/
with current_month_sales as
(
select
    datefromparts(
                    year(o.order_date),
                    month(o.order_date),
                    1
                    ) as sales_month,
    sum(oi.quantity * oi.price_per_unit) as sales_amount_per_month
    from orders as o
    left join order_items as oi
    on o.order_id = oi.order_id
    where o.order_date >= 
    (
        select 
            dateadd(
                    month,
                    -11,
                    datefromparts(
                    year(max(o2.order_date)),
                    month(max(o2.order_date)),
                    1)
                    )
        from orders as o2
    )
    group by datefromparts(
                    year(o.order_date),
                    month(o.order_date),
                    1
                    )
)
select
        sales_month,
        sales_amount_per_month,
        lag(sales_amount_per_month) over
        (order by sales_month) as previous_month_sales
from current_month_sales
order by sales_month;


/* Problem 5: Find every customer in the customers table whose 
customer_id does not appear in the orders.customer_id column. 
For those customers,display their customer ID, first name,
last name, state, and how much time has passed since
they registered (if you have it). */
select
    c.Customer_ID,
    c.first_name,
    c.last_name, 
    c.state
from customers as c
left join orders as o
on c.Customer_Id = o.customer_id
where o.order_id is null;

/* For confirmation: */
SELECT 
    COUNT(*) AS customers_with_no_orders
FROM customers AS c
LEFT JOIN orders AS o
    ON c.Customer_ID = o.customer_id
WHERE o.order_id IS NULL;

/* Problem 6: For each customer, add up the value of every order they have ever placed to calculate their total lifetime spending. 
Then compare all customers and assign a rank so the highest-spending customer appears first. */
with customer_lifetime_spending as
(
select
    c.Customer_ID,
    c.first_name,
    c.last_name,
    coalesce(sum(oi.quantity * oi.price_per_unit), 0) as lifetime_spending
from customers as c
left join orders as o
on c.Customer_ID = o.Customer_Id
left join order_items as oi
on o.order_id = oi.order_id
group by 
    c.Customer_ID,
    c.first_name,
    c.last_name
)
select
    Customer_ID,
    first_name,
    last_name,
    lifetime_spending,
    rank() over(order by lifetime_spending desc) as ranking
from customer_lifetime_spending 
order by ranking;

/* Problem 7: For each customer state, calculate the total sales generated by every product category. 
Then, within each state, find the category with the smallest total sales amount and display the state, 
category name, and that category’s total sales. */
with category_sales_amount_per_state as 
(
select
    c.state,
    cat.category_id,
    cat.category_name,
    sum(oi.quantity * oi.price_per_unit) as total_sales
from customers as c
join orders as o
on c.Customer_Id = o.customer_ID
join order_items as oi
on o.order_id = oi.order_id
join products as p 
on p.product_id = oi.product_id
join category as cat 
on cat.category_id = p.category_id
group by 
    c.state,
    cat.category_id,
    cat.category_name
),
ranked_categories as 
(
select 
    state,
    category_id,
    category_name,
    total_sales,
    rank() over(partition by state order by total_sales asc) as sales_rank
from category_sales_amount_per_state
)
select
    state,
    category_name,
    total_sales
from ranked_categories 
where sales_rank = 1
order by state;

/* Problem 8: Find all products whose current stock is below 10 units. */
select
    p.product_id,
    p.product_name,
    i.stock,
    i.last_stock_date,
    i.warehouse_id
from products as p
join inventory as i
on p.product_id = i.product_id
where i.stock < 10
order by i.stock asc;

/* Problem 9: Find all orders where the shipping date happened more than 3 days after the order date. */
select
    c.Customer_ID,
    c.first_name,
    c.last_name,
    s.shipping_providers,
    o.order_id,
    o.order_date,
    s.shipping_date,
    datediff(day, o.order_date, s.shipping_date) as shipping_duration,
    o.order_status
from customers as c
join orders as o
on c.Customer_ID = o.customer_id
join shipping as s 
on o.order_id = s.order_id
where s.shipping_date > dateadd(day,3,o.order_date)
order by shipping_duration desc;

/* Problem 10: Payment status distribution and percentage share. */
with payment_info as 
(
select
    payment_status,
    count(*) as number_of_payments
from payments
group by payment_status
)
select
    payment_status,
    number_of_payments,
    round(number_of_payments * 100.0 / sum(number_of_payments) over(),2) as percentage_share
from payment_info
order by percentage_share desc;

/* Problem 11: Top 5 sellers by revenue and order status performance. */
select top 5
    s.seller_id,
    s.seller_name,
    count(distinct o.order_id) as total_orders,
    count(distinct case when order_status = 'Completed' then o.order_id end) as completed_orders,
    count(distinct case when order_status = 'Inprogress' then o.order_id end) as inprogress_orders,
    count(distinct case when order_status = 'Returned' then o.order_id end) as returned_orders,
    count(distinct case when order_status = 'Cancelled' then o.order_id end) as cancelled_orders,
    cast(
        count(distinct case when order_status = 'Completed' then o.order_id end) * 100.0
        / count(distinct o.order_id)
        as decimal(5,2)
    ) as percentage_of_completed_orders,
    sum(oi.quantity * oi.price_per_unit) as total_revenue
from sellers as s
join orders as o
on s.seller_id = o.seller_id
join order_items as oi
on o.order_id = oi.order_id
group by 
    s.seller_id,
    s.seller_name
order by total_revenue desc;

/* Problem 12: Product unit profit ranking. */
select
    product_id,
    product_name,
    price,
    cogs,
    (price - cogs) as profit,
    rank() over(order by (price - cogs) desc) as ranking
from products
order by ranking asc;

/* Problem 13: Top 10 most returned products and return rate. */
select top 10
    p.product_id,
    p.product_name,
    sum(case when o.order_status = 'Returned' then oi.quantity else 0 end) as returned_products,
    cast(
        sum(case when o.order_status = 'Returned' then oi.quantity else 0 end) * 100.0
        / nullif(sum(oi.quantity),0)
        as decimal(5,2)
    ) as returned_percentage,
    sum(oi.quantity) as total_units_sold
from products as p
join order_items as oi
on oi.product_id = p.product_id
join orders as o
on o.order_id = oi.order_id
group by 
    p.product_id,
    p.product_name
order by returned_products desc;

/* Problem 14: Paid orders still Inprogress. */
select
    c.Customer_ID,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.order_status,
    p.payment_date,
    p.payment_status
from orders as o
join customers as c
on c.Customer_ID = o.customer_id
join payments as p
on p.order_id = o.order_id
where 
    o.order_status = 'Inprogress' 
and p.payment_status = 'Payment Successed'
order by o.order_date;

/* Problem 15: Inactive sellers relative to latest dataset order date. */
select 
    s.seller_id,
    s.seller_name,
    max(o.order_date) as last_order_date,
    coalesce(sum(oi.quantity * oi.price_per_unit),0) as total_sales
from sellers as s
left join orders as o
on o.seller_id = s.seller_id
left join order_items as oi
on o.order_id = oi.order_id
group by 
    s.seller_id,
    s.seller_name
having 
    max(o.order_date) < (
        select dateadd(month,-6,max(order_date)) 
        from orders
    )
    or max(o.order_date) is null
order by max(o.order_date);

/* Problem 16: Customer classification by returned-order count. */
select
    c.Customer_ID,
    c.first_name,
    c.last_name,
    count(distinct o.order_id) as total_orders,
    count(distinct case when o.order_status = 'Returned' then o.order_id end) as total_returns,
    case 
        when count(distinct case when o.order_status = 'Returned' then o.order_id end) > 5
        then 'Returning'
        else 'New'
    end as customer_category 
from customers as c
left join orders as o
on c.Customer_ID = o.customer_id
group by 
    c.Customer_ID,
    c.first_name,
    c.last_name
order by total_returns desc;

/* Problem 17: Cross-sell customers who bought AirPods 3rd Gen but not AirPods Max. */
select distinct
    c.Customer_ID,
    c.first_name,
    c.last_name,
    p.product_name as purchased_product,
    'Apple Airpods Max' as recommended_product,
    cat.category_name as matching_category
from customers as c
left join orders as o 
on o.customer_id = c.Customer_ID
left join order_items as oi
on o.order_id = oi.order_id
left join products as p 
on oi.product_id = p.product_id
left join category as cat
on cat.category_id = p.category_id 
where p.product_name = 'Apple AirPods 3rd Gen'
and not exists
(
    select 1
    from orders as o2
    left join order_items as oi2
    on o2.order_id = oi2.order_id
    left join products as p2
    on p2.product_id = oi2.product_id
    where o2.customer_id = c.Customer_ID
    and p2.product_name = 'Apple AirPods Max'
);

/* Problem 18: Top customers by orders within each state. */
with customer_summary as 
(
select
    c.Customer_ID,
    c.first_name,
    c.last_name,
    c.state,
    count(distinct o.order_id) as total_orders,
    coalesce(sum(oi.quantity * oi.price_per_unit),0) as total_sales 
from customers as c
left join orders as o
on c.Customer_ID = o.customer_id
left join order_items as oi
on o.order_id = oi.order_id
group by 
    c.Customer_ID,
    c.first_name,
    c.last_name,
    c.state
),
ranked_customers as 
(
select 
    Customer_ID,
    first_name,
    last_name,
    state,
    total_orders,
    total_sales,
    rank() over(partition by state order by total_orders desc) as ranking
from customer_summary
)
select
    Customer_ID,
    first_name,
    last_name,
    state,
    total_orders,
    total_sales,
    ranking
from ranked_customers
where ranking <= 5
order by 
    state,
    total_orders desc;

/* Problem 19: Shipping provider revenue, order count, and average shipping days. */
with order_summary as 
(
select
    o.order_id,
    o.order_date,
    s.shipping_date,
    s.shipping_providers,
    sum(oi.quantity * oi.price_per_unit) as order_revenue
from orders as o
left join order_items as oi
on o.order_id = oi.order_id
left join shipping as s
on s.order_id = oi.order_id
group by
    o.order_id,
    o.order_date,
    s.shipping_date,
    s.shipping_providers
)
select
    shipping_providers,
    sum(order_revenue) as total_revenue,
    count(order_id) as total_orders,
    cast(
        avg(
            cast(datediff(day, order_date, shipping_date) as decimal(10,2))
        ) as decimal(10,2)
    ) as average_shipping_days
from order_summary
group by shipping_providers;

/* Problem 20: Top 10 products with biggest revenue decline, 2022 vs 2023. */
with product_revenue as 
( 
select 
    cat.category_name,
    p.product_id,
    p.product_name,
    sum(case when year(o.order_date) = 2022 then oi.quantity * oi.price_per_unit else 0 end) as revenue_2022,
    sum(case when year(o.order_date) = 2023 then oi.quantity * oi.price_per_unit else 0 end) as revenue_2023
from products as p 
left join category as cat 
on p.category_id = cat.category_id
left join order_items as oi 
on p.product_id = oi.product_id
left join orders as o
on o.order_id = oi.order_id
group by 
    cat.category_name,
    p.product_id,
    p.product_name
)
select top 10
    category_name,
    product_id,
    product_name,
    revenue_2022,
    revenue_2023,
    round(
        (revenue_2023 - revenue_2022) * 100.0
        / nullif(revenue_2022,0),2
    ) as decrease_ratio
from product_revenue
where revenue_2022 > 0 
and revenue_2023 < revenue_2022
order by decrease_ratio;

/* Problem 21: Automatically reduce inventory when new order-item records are inserted. */
create trigger trg_reduce_inventory
on order_items
after insert 
as
begin

    update i
    set i.stock = i.stock - x.quantity_sold

    from inventory as i

    join
    (
        select
            product_id,
            sum(quantity) as quantity_sold
        from inserted
        group by product_id
    ) as x

    on i.product_id = x.product_id;

end;
